name: Release

on:
  workflow_dispatch:
  push:
    branches: [ "main", "beta" ]

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    uses: retejs/.github/.github/workflows/release.yml@main
    secrets: inherit
    with:
      dist: '.'
