name: Test Vite build 
run-name: Test Vite build for ${{ inputs.os }}

on:
  workflow_call:
    inputs:
      os:
        description: 'OS'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        required: true
        type: choice
        options:
        - ubuntu-latest
        - windows-latest
        - macos-latest

jobs:
  vite:
    name: Vite
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        version: [18]
    uses: ./.github/workflows/test-build.yml
    with:
      os: ${{ inputs.os }}
      stack: vite
      version: ${{ matrix.version }}
      node: 18
      features: "React render,${{ vars.FEATURES }}"
