name: Test build
run-name: Test build for ${{ inputs.stack }} v${{ inputs.version }} (Node.js ${{ inputs.node }}, ${{ inputs.os }})

on:
  workflow_call:
    inputs:
      os:
        description: 'OS'
        required: true
        type: string
      stack:
        description: 'Stack'
        required: true
        type: string
      version:
        description: 'Stack version'
        type: number
        required: true
      features:
        description: 'Features (comma separated)'
        required: true
        type: string
      node:
        description: 'Node version'
        type: string
        required: true
      kit-source:
        description: 'Rete Kit version source (npm or github)'
        type: string
        default: 'npm'
      kit-version:
        description: 'Rete Kit version/reference'
        type: string
        default: 'latest'
  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        required: true
        type: choice
        options:
        - ubuntu-latest
        - windows-latest
        - macos-latest
      stack:
        description: 'Stack'
        required: true
        type: choice
        options:
        - angular
        - react
        - react-vite
        - vue
        - vue-vite
        - vite
        - next
        - nuxt
        - lit-vite
      version:
        description: 'Stack version'
        type: number
        required: true
      features:
        description: 'Features (comma separated)'
        required: true
        type: string
      node:
        description: 'Node version'
        type: string
        required: true
      kit-source:
        description: 'Rete Kit version source (npm or github)'
        type: choice
        options:
        - npm
        - github
        default: 'npm'
      kit-version:
        description: 'Rete Kit version/reference'
        type: string
        default: 'latest'

jobs:
  build-app:
    name: v${{ inputs.version }} ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}
    - name: Install Rete Kit from NPM
      if: inputs.kit-source == 'npm'
      run: npm i -g rete-kit@${{ inputs.kit-version }}
    - uses: actions/checkout@v3
      if: inputs.kit-source == 'github'
      with:
        repository: retejs/rete-kit
        token: ${{ secrets.RETE_QA_PUBLIC_PULL }}
        ref: ${{ inputs.kit-version }}
    - name: Install Rete Kit from GitHub
      if: inputs.kit-source == 'github'
      run: |
        npm ci
        npm run build
        npm i -g .
    - name: Rete Kit version
      run: rete-kit -V
    - name: Bootstrapp application
      run: rete-kit app -n app -s ${{ inputs.stack }} -v ${{ inputs.version }} -f "${{ inputs.features }}"
    - name: Force install dependencies
      run: npm install
      working-directory: ./app
    - name: Build application
      run: npm run build
      env:
        CI: ""
      working-directory: ./app

